version: "3.8"

networks:
  nginx_network:
    external: true
    name: nginx_network

services:
  # Next.js service - Instance 1
  nextjs-1:
    build:
      context: .
      dockerfile: ./docker/next.js/Dockerfile
    ports:
      - "3001:3000"
    command: sh -c "npm run build && npm run start"
    container_name: KSS-IT-Committee-HP-nextjs-1
    restart: unless-stopped
    networks:
      - nginx_network
    volumes:
      - auth-data:/app/data
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 120s

  # Next.js service - Instance 2
  nextjs-2:
    build:
      context: .
      dockerfile: ./docker/next.js/Dockerfile
    expose:
      - "3000"
    command: sh -c "npm run build && npm run start"
    container_name: KSS-IT-Committee-HP-nextjs-2
    restart: unless-stopped
    networks:
      - nginx_network
    volumes:
      - auth-data:/app/data
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 120s

volumes:
  auth-data:
    driver: local