version: '3.8'

services:
  # Next.js service - Instance 1
  nextjs-1:
    build:
      context: .
      dockerfile: ./docker/next.js/Dockerfile
    expose:
      - "3000"
    command: sh -c "npm run build && npm run start"
    container_name: KSS-IT-Committee-HP-nextjs-1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  # Next.js service - Instance 2
  nextjs-2:
    build:
      context: .
      dockerfile: ./docker/next.js/Dockerfile
    expose:
      - "3000"
    command: sh -c "npm run build && npm run start"
    container_name: KSS-IT-Committee-HP-nextjs-2
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s

  # Nginx reverse proxy with load balancing
  nginx:
    build:
      context: ./docker/nginx/
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      nextjs-1:
        condition: service_healthy
      nextjs-2:
        condition: service_healthy
    container_name: KSS-IT-Committee-HP-nextjs-nginx
    restart: unless-stopped